project_name: HeatingMqttBridge

before:
  hooks:
    - go generate

builds:
  - binary: HeatingMqttBridge

    main: .
    ldflags:
      - -s -w

    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386

changelog:
  skip: true

archives:
  - id: traefik
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

release:
  draft: true
  prerelease: auto
