name: "Heating Mqtt Bridge"
version: "1.3"
slug: "roth2mqtt"
description: "This tiny bridge polls the central station of Roth EnergyLogic and pushes all information to an Mqtt broker."
url: https://github.com/MortenVinding/HeatingMqttBridge
startup: application
services:
  - mqtt: need
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386



image: docker run --rm --name heating -e HEATING=192.168.1.3 -e BROKER=192.168.1.2:1883 aklitzing/heatingmqttbridge
