name: "Heating Mqtt Bridge"
description: "This tiny bridge polls the central station of Roth EnergyLogic and pushes all information to an Mqtt broker."
version: "1.3"
slug: "roth2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
